apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appprojects
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/fascenvi/argo-platform-infra.git
              revision: main
              files:
                - path: tenants/*.yaml

          - list:
              elements:
                - env: dev
                - env: sdx
                - env: prd

  template:
    metadata:
      name: appproject-{{name}}-{{env}}
    spec:
      project: management

      source:
        repoURL: https://github.com/fascenvi/argo-platform-infra.git
        targetRevision: main
        path: appprojects/overlays/{{env}}

        kustomize:
          patches:
            - target:
                kind: AppProject
              patch: |
                - op: replace
                  path: /metadata/name
                  value: "{{name}}-{{env}}"              
                - op: replace
                  path: /spec/destinations/0/name
                  value: "{{name}}-{{env}}"


      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
