apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-appprojects
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # 1) Lê todos os tenants do repositório
          - git:
              repoURL: https://github.com/fascenvi/argo-platform-infra.git
              revision: main
              files:
                - path: tenants/*.yaml
          # 2) Lista de environments
          - list:
              elements:
                - environment: dev
                - environment: sdx
                - environment: prd

  template:
    metadata:
      name: appproject-{{name}}-{{environment}}
    spec:
      sourceRepos:
        - "*"
      destinations:
        - server: https://kubernetes.default.svc
          name: "{{name}}-{{environment}}"
          namespace: "*"
      destination:
        - server: https://kubernetes.default.svc
          name: "{{name}}-{{environment}}"
          namespace: "*"
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      namespaceResourceWhitelist:
        - group: "*"
          kind: "*"
