apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appprojects-management
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/fascenvi/argo-platform-infra.git
              revision: main
              files:
                - path: tenants/*.yaml

          - list:
              elements:
                - environment: dev
                - environment: sdx
                - environment: prd

  template:
    metadata:
      name: appproject-{{name}}-{{environment}}
    spec:
      project: management
      sourceRepos:
        - "*"  # Pode restringir a repositórios específicos
      destinations:
        - name: {{name}}-{{environment}}
          namespace: "*"
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      namespaceResourceWhitelist:
        - group: "*"
          kind: "*"