apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
spec:
  description: Managed AppProject

  sourceRepos:
    - "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
