apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: PLACEHOLDER
  namespace: argocd
spec:
  description: Development Environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*-dev'
      name: PLACEHOLDER
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'