apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd
  namespace: argocd
spec:
  description: Production Environment
  sourceRepos:
    - 'https://github.com/fascenvi/*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: 'apps'
      kind: Deployment
  preserveResourcesOnDeletion: true