apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd
  namespace: argocd
spec:
  description: Production Environment
  sourceRepos:
    - 'https://github.com/fascenvi/*'
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: 'apps'
      kind: Deployment