apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: '{{path.basename}}-prd'
  namespace: argocd
spec:
  description: '{{path.basename}} PROD environment'
  sourceRepos:
    - https://github.com/org/apps-*
  destinations:
    - namespace: '{{path.basename}}-prd-*'
      server: https://kubernetes.default.svc
  syncWindows:
    - kind: deny
      schedule: '* * * * *'
      duration: 24h
      manualSync: true
